[[architecture]]
machine = "examples"
workdir = "./_examples"


[[machine]]
name = "examples"
group = "default"
connection = "local"


[marshalDatabase]
Path = "_examples/tmp/01_architecture.db"


# kak: filetype=ini
