[[provider]]
name = "local"
type = "local"
workdir = "./_examples/tmp/provision"

[[machine]]
name = "build machine"
provider = "local"


[[provision]]
machine = "build machine"
script = """
"""

[[resource]]
machine = "build machine"
path = "/opt/motly/resources/hash"
script = """
"""

[[provision]]


[marshalDatabase]
Path = "_examples/tmp/provision.db"

# kak: filetype=ini
